const fs = require("fs");
const path = require("path");
const assert = require("assert");

const js = fs.readFileSync(path.join(__dirname, "../public/office-auth.js"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "../public/office-shell.css"), "utf8");
const floor = fs.readFileSync(path.join(__dirname, "../index.html"), "utf8");

const labels = [
  "Home", "Orders", "Enquiries", "My tasks", "Dropdowns", "Users",
  "Task times", "Planning", "Debtors", "Production Tasks", "Production", "Workers", "Metrics",
  "QC Reports", "Activity", "Schedule", "Log Out", "Change access code"
];
labels.forEach((label) => {
  assert.ok(js.indexOf('"' + label + '"') !== -1 || js.indexOf(">" + label + "<") !== -1, "office menu missing " + label);
});

assert.ok(js.indexOf("/enquiries") !== -1);
assert.ok(js.indexOf("/tasks") !== -1);
assert.ok(js.indexOf("Office schedule") === -1, "office schedule is an Orders subpage");
assert.ok(js.indexOf("Glass rates") === -1, "glass rates is an Orders subpage");
assert.ok(js.indexOf("Production cost") === -1, "production cost is an Orders subpage");
assert.ok(js.indexOf('"/schedule"') === -1);
assert.ok(js.indexOf("/planning") !== -1, "planning is an office page");
assert.ok(js.indexOf('"Planning"') !== -1);

const officeJs = fs.readFileSync(path.join(__dirname, "office.js"), "utf8");
assert.ok(officeJs.indexOf("listMyCompletedTasks") !== -1);
assert.ok(officeJs.indexOf("req.query.done") !== -1);
const indexJs = fs.readFileSync(path.join(__dirname, "index.js"), "utf8");
assert.ok(indexJs.indexOf("/tasks/completed") !== -1);
assert.ok(indexJs.indexOf("/tasks/team") !== -1);
const tasksHtml = fs.readFileSync(path.join(__dirname, "../public/tasks.html"), "utf8");
assert.ok(tasksHtml.indexOf("/tasks/completed") !== -1);
assert.ok(tasksHtml.indexOf("/tasks/team") !== -1);
assert.ok(tasksHtml.indexOf(">To do<") !== -1);
assert.ok(tasksHtml.indexOf(">Completed<") !== -1);
assert.ok(tasksHtml.indexOf(">Mine<") !== -1);
assert.ok(tasksHtml.indexOf(">Other people<") !== -1);
assert.ok(tasksHtml.indexOf("done=1") !== -1);
assert.ok(tasksHtml.indexOf("personFilter") !== -1);
assert.ok(tasksHtml.indexOf("typeFilter") !== -1);
assert.ok(tasksHtml.indexOf(">Quoting<") !== -1);
assert.ok(tasksHtml.indexOf(">Costing<") !== -1);
assert.ok(tasksHtml.indexOf("scope=mine") !== -1);
assert.ok(tasksHtml.indexOf("canViewAll") !== -1);
assert.ok(tasksHtml.indexOf("scope=all") !== -1);
assert.ok(tasksHtml.indexOf("Assigned to <b>") !== -1);
assert.ok(tasksHtml.indexOf("typeHeading") !== -1);
assert.ok(officeJs.indexOf("canViewAll") !== -1);
assert.ok(js.indexOf("/?view=production") !== -1);
assert.ok(js.indexOf("/?view=production-tasks") !== -1);
assert.ok(js.indexOf('"Production Tasks"') !== -1);
assert.ok(js.indexOf("productiontasks") !== -1);
assert.ok(floor.indexOf('id="link-production-tasks"') !== -1);
assert.ok(floor.indexOf("function showProductionTasks") !== -1);
assert.ok(/function logout\([\s\S]*setFloorView\(''\)/.test(floor), "logout must leave Production Tasks view so Admin opens Home");
assert.ok(floor.indexOf('id="rolesPageTitle"') !== -1);
assert.ok(floor.indexOf("/?view=floor") === -1, "Floor is Home, not a second menu item");
assert.ok(js.indexOf('id="link-floor"') === -1);
assert.ok(floor.indexOf('id="link-floor"') === -1, "floor sidebar link must be gone");
assert.ok(floor.indexOf("getFloorLayout") !== -1);
assert.ok(floor.indexOf("startFloorTwin") !== -1);
assert.ok(floor.indexOf("twin-actor") !== -1);
assert.ok(floor.indexOf("twin-arc") !== -1, "welding uses a live arc");
assert.ok(floor.indexOf("twin-pile") !== -1, "ready goods are pallets, not text labels on the map");
assert.ok(floor.indexOf("floor-pop") !== -1);
assert.ok(floor.indexOf("floor-count-btn") !== -1);
assert.ok(floor.indexOf("task-counts") !== -1);
assert.ok(floor.indexOf("is-ready") !== -1);
assert.ok(floor.indexOf("is-active") !== -1);
assert.ok(floor.indexOf("is-paused") !== -1);
assert.ok(floor.indexOf("road-map") !== -1);
assert.ok(floor.indexOf("floor-atlas") !== -1);
assert.ok(floor.indexOf("facility-floor.png") !== -1);
assert.ok(floor.indexOf("job-cart") !== -1);
assert.ok(floor.indexOf("New orders") !== -1);
assert.ok(floor.indexOf("Ready for welding") !== -1);
assert.ok(floor.indexOf("Ready for assembly") !== -1);
assert.ok(floor.indexOf("Pre-powder QC") !== -1);
assert.ok(floor.indexOf("Final QC") !== -1);
assert.ok(floor.indexOf("FLOOR_EXTRA_BAYS") !== -1, "unnamed live workers stand at leftover benches, not in the aisle");
assert.ok(floor.indexOf("p === 'welding' || p === 'tagging'") !== -1, "tagging uses the weld animation");
assert.ok(floor.indexOf("Finished goods") !== -1);
assert.ok(floor.indexOf("bindFloorDrag") !== -1, "people and piles can be dragged");
assert.ok(floor.indexOf("sd-floor-pos") !== -1);
assert.ok(floor.indexOf("Reset layout") !== -1);
assert.ok(floor.indexOf("FLOOR_QC_DOORS") === -1, "do not pin QC on the doors");
assert.ok(floor.indexOf("data-floor-door") === -1, "do not render door spots");
assert.ok(officeJs.indexOf("/api/office/floor-layout") !== -1);
assert.ok(floor.indexOf("id=\"floorPopover\"") !== -1);
assert.ok(floor.indexOf("id=\"confirmModal\"") !== -1);
assert.ok(/canSeeOffice[\s\S]{0,80}showTaskPicker/.test(floor), "Admin login still opens Home");
assert.ok(/chooser\.classList\.toggle\('d-none-view', !tasksOnly\)/.test(floor), "task cards are hidden on Home");
assert.ok(/if \(tasksOnly\)[\s\S]{0,200}loadMyTaskCounts/.test(floor), "task cards load only on Production Tasks");
assert.ok(floor.indexOf("safeNextPath") === -1 || floor.indexOf("if (next && session.canSeeOffice)") === -1, "office login must not skip Home via next=");
assert.ok(floor.indexOf('id="homeScore"') !== -1);
assert.ok(floor.indexOf("loadHomeScore") !== -1);
assert.ok(floor.indexOf("Your duration for this order is") !== -1);
assert.ok(floor.indexOf("Estimated finish") !== -1);
assert.ok(floor.indexOf("lunch is not counted") !== -1);
assert.ok(floor.indexOf("Time left") !== -1);
assert.ok(floor.indexOf("data-priorworkms") !== -1);
assert.ok(floor.indexOf("estimateCompletionAt") !== -1);
assert.ok(floor.indexOf("getMyCompletedWork") !== -1);
assert.ok(floor.indexOf("updateCompletedSteelUsage") !== -1);
assert.ok(floor.indexOf("Edit steel usage") !== -1);
assert.ok(floor.indexOf("openEditCompletedSteel") !== -1);
assert.ok(floor.indexOf("Steel logged") !== -1);
assert.ok(floor.indexOf("steelRowTargetId") !== -1);
assert.ok(floor.indexOf("is-over-edit") !== -1);
assert.ok(floor.indexOf('id="view-completed"') !== -1);
assert.ok(floor.indexOf('id="completedWorkBtn"') !== -1);
assert.ok(floor.indexOf('pane-completed') !== -1);
assert.ok(floor.indexOf("bi-trophy-fill") !== -1);
assert.ok(floor.indexOf("bi-alarm-fill") !== -1);
assert.ok(floor.indexOf("pauses do not count") !== -1 || floor.indexOf("Pauses do not count") !== -1);
assert.ok(floor.indexOf("/api/office/enquiries/dashboard") !== -1);
assert.ok(floor.indexOf("Quoted waiting") !== -1);
assert.ok(floor.indexOf("Quotes this month") !== -1);
assert.ok(js.indexOf("hadOffice") !== -1);
assert.ok(/hadOffice[\s\S]{0,180}location\.replace\("\/"\)/.test(js), "office login from another page must open Home");
assert.ok(js.indexOf("/?view=workers") !== -1);
assert.ok(js.indexOf("/?view=metrics") !== -1);
assert.ok(js.indexOf("/?view=qc") !== -1);
assert.ok(js.indexOf("/?view=activity") !== -1);
assert.ok(js.indexOf("/?view=schedule") !== -1);
assert.ok(js.indexOf("sd-sidebar-scroll") !== -1);
assert.ok(js.indexOf("Change access code") !== -1);
assert.ok(floor.indexOf("changePassName") !== -1);
assert.ok(js.indexOf("Logged in as") !== -1);
assert.ok(js.indexOf("sdPaintOfficeWho") !== -1);
assert.ok(js.indexOf("officeWhoTitle") !== -1);
assert.ok(floor.indexOf("Logged in as") !== -1);
assert.ok(floor.indexOf("sidebarWhoRole") !== -1);
assert.ok(floor.indexOf("loggedInJobTitle") !== -1);
assert.ok(floor.indexOf("session.jobTitle") !== -1);
assert.ok(js.indexOf("sdHideUsersLink") !== -1);
assert.ok(floor.indexOf("openChangePassword") !== -1);
assert.ok(floor.indexOf("Change access code") !== -1);
assert.ok(js.indexOf("sdWarnPersistence") !== -1);
assert.ok(css.indexOf(".sd-persist-banner") !== -1);

const processJs = fs.readFileSync(path.join(__dirname, "../public/enquiry-process.js"), "utf8");
assert.ok(processJs.indexOf("productNamesLine") !== -1);
assert.ok(processJs.indexOf("Value incl VAT") !== -1);
assert.ok(processJs.indexOf("sd-quote-totals") !== -1);
assert.ok(processJs.indexOf("delivery_incl_vat") !== -1);
assert.ok(processJs.indexOf('complete_cost_sheet') !== -1);
assert.ok(!/complete_cost_sheet[\s\S]{0,200}valuesTable/.test(processJs), "cost sheet must not ask for product values");
assert.ok(processJs.indexOf("Add another cost sheet") !== -1);
assert.ok(processJs.indexOf("cost_sheets") !== -1);
assert.ok(processJs.indexOf("Paste the file link or path") !== -1);
assert.ok(processJs.indexOf("quote_assignee") !== -1);
assert.ok(processJs.indexOf("Request approval from (optional)") !== -1);
assert.ok(processJs.indexOf("Quoting person") !== -1);
assert.ok(processJs.indexOf("enquiryRoles") !== -1);
assert.ok(processJs.indexOf("rolePerson") !== -1);
assert.ok(processJs.indexOf("Costing person if rejected") !== -1);
assert.ok(processJs.indexOf("reject_costing") !== -1);
assert.ok(processJs.indexOf("Why reject costing") !== -1);
assert.ok(processJs.indexOf("costingRejectReasons") !== -1);
assert.ok(processJs.indexOf("Wrong product or specifictions") !== -1);
assert.ok(processJs.indexOf("quote_no") !== -1);
assert.ok(processJs.indexOf("Issue another quote") !== -1 || processJs.indexOf("Previous quote") !== -1);
assert.ok(processJs.indexOf("This is option") !== -1);
assert.ok(processJs.indexOf("complete_quote_option") !== -1);
assert.ok(processJs.indexOf("quote_option") !== -1);
assert.ok(processJs.indexOf("Client wants changes") !== -1 || processJs.indexOf("recost") !== -1);
assert.ok(processJs.indexOf("Last quotation numbers") !== -1);
assert.ok(processJs.indexOf("correspondence_links") !== -1);
assert.ok(processJs.indexOf("Correspondance link") !== -1);
assert.ok(processJs.indexOf("Copy link") !== -1);
assert.ok(processJs.indexOf("sd-open-mail") !== -1);
assert.ok(processJs.indexOf('f.group === "correspondence"') !== -1);
assert.ok(processJs.indexOf("Drop the Outlook email") === -1, "do not attach the Outlook .msg");
assert.ok(processJs.indexOf("correspondence_files") === -1, "UI must not upload the email file");
assert.ok(processJs.indexOf("data-outlook-drop") === -1);
assert.ok(processJs.indexOf("Save email from Outlook") === -1);
assert.ok(processJs.indexOf("sd-timeline-fold") !== -1);
assert.ok(processJs.indexOf("data-open-file") !== -1 || processJs.indexOf("data-copy-link") !== -1);
assert.ok(processJs.indexOf("Files") !== -1);
assert.ok(processJs.indexOf("Correspondance link") !== -1);
assert.ok(processJs.indexOf("Request access") !== -1);
assert.ok(processJs.indexOf("request_access") !== -1);
assert.ok(processJs.indexOf("grant_access") !== -1);
assert.ok(processJs.indexOf("Create order from this enquiry") !== -1);
assert.ok(processJs.indexOf("/orders/from-enquiry") !== -1);
assert.ok(processJs.indexOf("Follow-up") !== -1);
assert.ok(processJs.indexOf("followUpPeople") !== -1);
assert.ok(processJs.indexOf("Who follows up after 7 days?") === -1);
assert.ok(processJs.indexOf("Who owns the next follow-up?") === -1);
assert.ok(processJs.indexOf("Supplier quotation") !== -1);
assert.ok(processJs.indexOf("Costing resumes with") !== -1);
assert.ok(processJs.indexOf("complete_supplier") !== -1);
assert.ok(/complete_supplier[\s\S]{0,400}fileBlock/.test(processJs));
assert.ok(processJs.indexOf("/create-order") === -1, "process button opens the split-order form");
assert.ok(officeJs.indexOf("createOrderFromEnquiry") !== -1);
assert.ok(officeJs.indexOf("/create-order") !== -1);
assert.ok(officeJs.indexOf("/create-order-draft") !== -1);
assert.ok(officeJs.indexOf("createOrdersFromEnquiryForm") !== -1);
assert.ok(officeJs.indexOf("applyCaptureRoute") !== -1);
assert.ok(officeJs.indexOf("isAutoCaptureStatus") !== -1);
const quoteOptJs = fs.readFileSync(path.join(__dirname, "quote-options.js"), "utf8");
assert.ok(quoteOptJs.indexOf("liveQuoteOptions") !== -1);
const pipelineJs = fs.readFileSync(path.join(__dirname, "enquiry-pipeline.js"), "utf8");
assert.ok(pipelineJs.indexOf("complete_quote_option") !== -1);
assert.ok(pipelineJs.indexOf("function classifyCapture") !== -1);
assert.ok(pipelineJs.indexOf("Save Correspondance link") !== -1);
assert.ok(pipelineJs.indexOf("Save email from Outlook") === -1);
assert.ok(pipelineJs.indexOf("outlookAddin") === -1);
assert.ok(pipelineJs.indexOf("requireCorrespondence") !== -1);
assert.ok(officeJs.indexOf("correspondence_links") !== -1);
assert.ok(pipelineJs.indexOf("function applyCaptureRoute") !== -1);
assert.ok(pipelineJs.indexOf("Waiting on clients personal details") !== -1);
assert.ok(pipelineJs.indexOf("Waiting on clients specifictions") !== -1);
assert.ok(pipelineJs.indexOf("Upload supplier quotation") !== -1);
assert.ok(officeJs.indexOf("listAccessInbox") !== -1);
assert.ok(tasksHtml.indexOf("Access requests") !== -1);
assert.ok(tasksHtml.indexOf("Outlook email") === -1);
assert.ok(tasksHtml.indexOf("Correspondance link") !== -1);

assert.ok(processJs.indexOf("sd-file-row") !== -1);
assert.ok(processJs.indexOf("sd-timeline") !== -1);
assert.ok(processJs.indexOf("Lifespan") !== -1);
const enquiriesHtml = fs.readFileSync(path.join(__dirname, "../public/enquiries.html"), "utf8");
assert.ok(enquiriesHtml.indexOf('id="period"') !== -1);
assert.ok(enquiriesHtml.indexOf('id="quotedOnly"') !== -1);
assert.ok(enquiriesHtml.indexOf('id="totIncl"') !== -1);
assert.ok(enquiriesHtml.indexOf('id="lineTotIncl"') !== -1, "product modal totals must not reuse the sheet totIncl id");
assert.ok(enquiriesHtml.indexOf("Quoted only") !== -1);
assert.ok(enquiriesHtml.indexOf('id="captureMask"') !== -1, "New enquiry must open a capture modal");
assert.ok(/<input id="cap_enquiry_no"[^>]*>/.test(enquiriesHtml));
assert.ok(!/<input id="cap_enquiry_no"[^>]*\breadonly\b/.test(enquiriesHtml), "new enquiry number must be editable");
assert.ok(enquiriesHtml.indexOf("Next number fills in") !== -1);
assert.ok(enquiriesHtml.indexOf("lockCaptureEnquiryNo(false)") !== -1, "enquiry number stays editable on new and edit");
assert.ok(enquiriesHtml.indexOf("previous_enquiry_no") !== -1, "edit must send the old number so files can move");
assert.ok(enquiriesHtml.indexOf("You can change this number") !== -1);
assert.ok(enquiriesHtml.indexOf("removeAttribute(\"readonly\")") !== -1);
assert.ok(enquiriesHtml.indexOf("formatTypedEnquiryNoField") !== -1);
assert.ok(enquiriesHtml.indexOf("create_only") !== -1);
assert.ok(enquiriesHtml.indexOf("Enter a Correspondance link.") !== -1);
assert.ok(enquiriesHtml.indexOf("cap_correspondence") !== -1);
assert.ok(enquiriesHtml.indexOf("captureCorrespondence") !== -1);
assert.ok(enquiriesHtml.indexOf('id="captureCorrespondence" hidden') === -1, "Correspondance link field must be visible on capture");
assert.ok(enquiriesHtml.indexOf("capture-correspondence") !== -1);
assert.ok(enquiriesHtml.indexOf("openCaptureForCorrespondence") !== -1);
assert.ok(enquiriesHtml.indexOf("Paste the file link or path") !== -1);
assert.ok(enquiriesHtml.indexOf("captureWouldCost") !== -1);
assert.ok(enquiriesHtml.indexOf("#grid {") !== -1 || enquiriesHtml.indexOf("#grid{") !== -1);
assert.ok(enquiriesHtml.indexOf("table { border-collapse:separate; border-spacing:0; min-width:3200px") === -1, "enquiry grid min-width must not apply to all tables");
assert.ok(enquiriesHtml.indexOf("openCapture") !== -1);
assert.ok(enquiriesHtml.indexOf("No enquiries yet") !== -1);
assert.ok(enquiriesHtml.indexOf("rows.length && filtered") !== -1, "empty sheet must not look like a failed filter");
assert.ok(enquiriesHtml.indexOf("Clear all enquiries") === -1, "Clear all enquiries must not be on the Enquiries page");
assert.ok(enquiriesHtml.indexOf("/api/office/enquiries/clear-all") === -1);
assert.ok(enquiriesHtml.indexOf("openOnboard") !== -1);
assert.ok(enquiriesHtml.indexOf("/api/office/enquiries/onboard") !== -1);
assert.ok(enquiriesHtml.indexOf("Where is this enquiry now?") !== -1);
assert.ok(enquiriesHtml.indexOf("sd-enq-draft") !== -1, "unsaved enquiry forms keep a per-user draft");
assert.ok(enquiriesHtml.indexOf("localStorage.setItem(key, JSON.stringify(data))") !== -1, "enquiry drafts survive closing the tab");
assert.ok(enquiriesHtml.indexOf("One cost sheet per product") !== -1);
assert.ok(enquiriesHtml.indexOf("obCostList") !== -1);
assert.ok(enquiriesHtml.indexOf("data-ob-add-cost") !== -1);
assert.ok(enquiriesHtml.indexOf('if (e.target.id === "onboardMask") closeOnboard()') === -1, "Add existing enquiry must not close on outside click");
assert.ok(enquiriesHtml.indexOf('if (e.target.id === "captureMask") closeCapture()') === -1, "New enquiry must not close on outside click");
assert.ok(enquiriesHtml.indexOf('if (e.target.id === "mask") closeModal(false)') === -1, "product form must not close on outside click");
assert.ok(enquiriesHtml.indexOf('if (e.target.id === "specMask") closeSpec(false)') === -1, "spec form must not close on outside click");
assert.ok(processJs.indexOf('if (e.target.id === "sdProcessMask") closeProcess()') === -1, "process form must not close on outside click");
assert.ok(officeJs.indexOf("deleteAllEnquiries") !== -1);
assert.ok(officeJs.indexOf("onboardEnquiry") !== -1);
assert.ok(enquiriesHtml.indexOf("data-edit-enquiry") !== -1);
assert.ok(enquiriesHtml.indexOf("Edit enquiry") !== -1);
assert.ok(enquiriesHtml.indexOf("bi-pencil") !== -1);
assert.ok(enquiriesHtml.indexOf("bi-list-task") !== -1);
assert.ok(enquiriesHtml.indexOf("data-open-process") !== -1);
assert.ok(enquiriesHtml.indexOf("onclick=\"saveAll()\"") === -1, "enquiries sheet must not save by editing cells");
assert.ok(enquiriesHtml.indexOf("table.oninput") === -1, "grid must not edit cells in place");
assert.ok(enquiriesHtml.indexOf('["opened_at_label"') === -1, "enquiries sheet must not show Opened");
assert.ok(enquiriesHtml.indexOf("OPENED") === -1, "enquiries sheet must not show Opened");
assert.ok(enquiriesHtml.indexOf('["lifespan_label"') === -1, "enquiries sheet must not show Lifespan");
assert.ok(enquiriesHtml.indexOf(">LIFESPAN<") === -1, "enquiries sheet must not show Lifespan");
assert.ok(enquiriesHtml.indexOf("· update") === -1, "status update must not live in the STATUS column");
assert.ok(enquiriesHtml.indexOf("cell-btn") === -1, "status column must be text, not a button");
assert.ok(enquiriesHtml.indexOf("openView") !== -1, "clicking an enquiry row must open a view popup");
assert.ok(enquiriesHtml.indexOf("VALUE (Incl VAT)") !== -1);
assert.ok(enquiriesHtml.indexOf('id="totVat"') !== -1);
assert.ok(enquiriesHtml.indexOf("viewMask") !== -1);
assert.ok(enquiriesHtml.indexOf("/enquiries/dashboard") !== -1, "sheet must link to the dashboard");
assert.ok(enquiriesHtml.indexOf(">Dashboard<") !== -1);
assert.ok(enquiriesHtml.indexOf("/enquiries/replies") !== -1, "sheet must link to standard email replies");
assert.ok(enquiriesHtml.indexOf(">Email replies<") !== -1);
assert.ok(enquiriesHtml.indexOf("/enquiries/bookings") !== -1, "sheet must link to showroom bookings");
assert.ok(enquiriesHtml.indexOf(">Showroom bookings<") !== -1);
assert.ok(enquiriesHtml.indexOf('id="assignedToMe"') !== -1);
assert.ok(enquiriesHtml.indexOf("Assigned to me") !== -1);
assert.ok(enquiriesHtml.indexOf('id="openClosed"') !== -1);
assert.ok(enquiriesHtml.indexOf("typedEnquiryNoQuery") !== -1, "searching an enquiry number must still find a rejected row");
assert.ok(enquiriesHtml.indexOf("Closed jobs stay on the system") !== -1);
assert.ok(enquiriesHtml.indexOf('id="statusFilter"') !== -1);
assert.ok(enquiriesHtml.indexOf("Download CSV") !== -1);
assert.ok(enquiriesHtml.indexOf("QUOTE INCL VAT") !== -1);
assert.ok(enquiriesHtml.indexOf("ASSIGNED TO") !== -1);
assert.ok(enquiriesHtml.indexOf("data-create-order") !== -1);
assert.ok(enquiriesHtml.indexOf("/orders/from-enquiry") !== -1);
assert.ok(enquiriesHtml.indexOf("Save anyway") !== -1);
assert.ok(enquiriesHtml.indexOf("has-filter::after") === -1, "do not fake column filters with a triangle");
assert.ok(enquiriesHtml.indexOf("/enquiry-process.js?v=corr-links") !== -1);
assert.ok(processJs.indexOf("sd-option-line") !== -1);
assert.ok(processJs.indexOf("data-option-lines") !== -1);
assert.ok(processJs.indexOf("sd-process-fields") !== -1);
assert.ok(processJs.indexOf("Add another Correspondance link") !== -1);
assert.ok(processJs.indexOf("data-correspondence-link") !== -1);
assert.ok(enquiriesHtml.indexOf("Add another Correspondance link") !== -1);
assert.ok(enquiriesHtml.indexOf("data-corr-links") !== -1);
assert.ok(enquiriesHtml.indexOf("Rejection reason") !== -1);
assert.ok(enquiriesHtml.indexOf("closeReason") !== -1);
assert.ok(enquiriesHtml.indexOf("costingRejectReason") !== -1);
assert.ok(enquiriesHtml.indexOf("Costing rejected") !== -1);
assert.ok(enquiriesHtml.indexOf("form-head-err") !== -1);
assert.ok(enquiriesHtml.indexOf("data-save=\"capture\"") !== -1);
assert.ok(enquiriesHtml.indexOf("offerTakenNumber") !== -1);
assert.ok(enquiriesHtml.indexOf("Use next number") !== -1);
assert.ok(enquiriesHtml.indexOf("Saving…") !== -1);
const ordersHtml = fs.readFileSync(path.join(__dirname, "../public/orders.html"), "utf8");
assert.ok(ordersHtml.indexOf("orderLife") !== -1, "order view shows the full journey");
assert.ok(ordersHtml.indexOf("fillOrderLife") !== -1);
assert.ok(ordersHtml.indexOf("Journey") !== -1);
assert.ok(ordersHtml.indexOf("/life") !== -1);
assert.ok(officeJs.indexOf("/api/office/orders/:orderNumber/life") !== -1);
assert.ok(officeJs.indexOf("/api/office/enquiries/:enquiryNo/life") !== -1);
assert.ok(officeJs.indexOf("collectOrderLife") !== -1);
assert.ok(processJs.indexOf("Journey") !== -1, "enquiry process shows the full journey");
assert.ok(processJs.indexOf("/life") !== -1);
assert.ok(processJs.indexOf("sdJourney") !== -1);
assert.ok(ordersHtml.indexOf("ENQUIRY NO") === -1, "enquiry number stays linked but is not a sheet column");
assert.ok(ordersHtml.indexOf("enquiry_no") !== -1);
assert.ok(ordersHtml.indexOf("Amount paid (Incl VAT)") !== -1);
assert.ok(ordersHtml.indexOf("AMOUNT PAID (Incl VAT)") !== -1);
assert.ok(ordersHtml.indexOf("including 15% VAT") !== -1);
assert.ok(ordersHtml.indexOf("Paid in full") !== -1);
assert.ok(ordersHtml.indexOf("f_paid_in_full") !== -1);
assert.ok(ordersHtml.indexOf("cents <= 1") !== -1);
assert.ok(ordersHtml.indexOf("price_incl_vat: document.getElementById(\"f_price_incl_vat\")") !== -1);
assert.ok(ordersHtml.indexOf("data-edit-order") !== -1);
assert.ok(ordersHtml.indexOf("wrap-text") === -1);
assert.ok(enquiriesHtml.indexOf("wrap-text") === -1, "enquiry sheet rows must not wrap");
assert.ok(enquiriesHtml.indexOf("height:36px") !== -1);
assert.ok(ordersHtml.indexOf("addRow()") === -1);
assert.ok(ordersHtml.indexOf("/orders/schedule") !== -1);
assert.ok(ordersHtml.indexOf("Production schedule") !== -1);
assert.ok(ordersHtml.indexOf("/orders/delivery") !== -1);
assert.ok(ordersHtml.indexOf("Delivery summary") !== -1);
assert.ok(ordersHtml.indexOf("/orders/job-card") !== -1);
assert.ok(ordersHtml.indexOf("/orders/to-order") !== -1);
assert.ok(ordersHtml.indexOf("To order") !== -1);
assert.ok(ordersHtml.indexOf("/orders/paint-shop") !== -1);
assert.ok(ordersHtml.indexOf("Paint shop") !== -1);
assert.ok(ordersHtml.indexOf("Generate job card") !== -1);
assert.ok(ordersHtml.indexOf("data-job-card") !== -1);
assert.ok(ordersHtml.indexOf("data-open-job-card") !== -1);
assert.ok(ordersHtml.indexOf("Open / print job card") !== -1);
assert.ok(ordersHtml.indexOf("<select id=\"f_status\">") === -1, "status is not a manual dropdown");
assert.ok(ordersHtml.indexOf("id=\"f_status\" readonly") !== -1);
assert.ok(ordersHtml.indexOf("Mark selected as important") !== -1);
assert.ok(ordersHtml.indexOf("Clear all orders") !== -1);
assert.ok(ordersHtml.indexOf("/api/office/orders/clear-all") !== -1);
assert.ok(officeJs.indexOf("deleteAllOrders") !== -1);
const scheduleHtml = fs.readFileSync(path.join(__dirname, "../public/orders-schedule.html"), "utf8");
assert.ok(scheduleHtml.indexOf("Production schedule") !== -1);
assert.ok(scheduleHtml.indexOf("/orders") !== -1);
assert.ok(scheduleHtml.indexOf("/orders/delivery") !== -1);
assert.ok(scheduleHtml.indexOf("/orders/job-card") !== -1);
assert.ok(scheduleHtml.indexOf("/orders/paint-shop") !== -1);
assert.ok(scheduleHtml.indexOf("sdRequireOffice(\"orders\")") !== -1);
assert.ok(scheduleHtml.indexOf("addRow()") === -1, "orders auto-fill the schedule");
assert.ok(scheduleHtml.indexOf("Latest Delivery") !== -1);
assert.ok(scheduleHtml.indexOf("<optgroup") === -1, "do not stamp a dropdown in every cell");
assert.ok(scheduleHtml.indexOf("codeSelect") === -1);
assert.ok(scheduleHtml.indexOf("id=\"picker\"") !== -1);
assert.ok(scheduleHtml.indexOf("id=\"q\"") !== -1);
assert.ok(scheduleHtml.indexOf("unplanned") !== -1);
assert.ok(scheduleHtml.indexOf("frozenWeek") !== -1);
assert.ok(scheduleHtml.indexOf("ITEM TYPE") !== -1);
assert.ok(scheduleHtml.indexOf("CATEGORY") !== -1);
assert.ok(scheduleHtml.indexOf("PRODUCT") !== -1);
assert.ok(scheduleHtml.indexOf("PROVINCE") !== -1);
assert.ok(scheduleHtml.indexOf("COURIER") !== -1);
assert.ok(scheduleHtml.indexOf("WAYBILL") !== -1);
assert.ok(scheduleHtml.indexOf("STATUS") !== -1);
assert.ok(scheduleHtml.indexOf("id=\"meta\"") !== -1, "order columns sit in a frozen pane");
assert.ok(scheduleHtml.indexOf("meta-pane") !== -1);
assert.ok(scheduleHtml.indexOf("overflow:auto hidden") === -1, "left pane must not steal horizontal scroll");
assert.ok(scheduleHtml.indexOf("overflow-x:hidden") !== -1);
assert.ok(scheduleHtml.indexOf("max-width:min(var(--lock), 50%)") === -1, "do not crush order headers");
assert.ok(scheduleHtml.indexOf("overflow-x:auto") !== -1, "calendar pane keeps horizontal scroll");
assert.ok(officeJs.indexOf("SCHEDULE_WORKDAYS") !== -1);
assert.ok(officeJs.indexOf("workdays(start, 60)") === -1);
assert.ok(scheduleHtml.indexOf("th.day { text-transform:none") !== -1 || scheduleHtml.indexOf("th.day { text-transform: none") !== -1);
assert.ok(scheduleHtml.indexOf("07-Jan") !== -1 || scheduleHtml.indexOf("order_date_label") !== -1);
assert.ok(indexJs.indexOf("/orders/schedule") !== -1);
assert.ok(indexJs.indexOf("/orders/delivery") !== -1);
assert.ok(indexJs.indexOf("/orders/job-card") !== -1);
assert.ok(indexJs.indexOf("/orders/job-card/existing") !== -1);
assert.ok(indexJs.indexOf("/orders/to-order") !== -1);
assert.ok(indexJs.indexOf("/orders/paint-shop") !== -1);
assert.ok(indexJs.indexOf("/orders/from-enquiry") !== -1);
const fromEnquiryHtml = fs.readFileSync(path.join(__dirname, "../public/orders-from-enquiry.html"), "utf8");
assert.ok(fromEnquiryHtml.indexOf("Create orders from enquiry") !== -1);
assert.ok(fromEnquiryHtml.indexOf("Amount paid (Incl VAT)") !== -1);
assert.ok(fromEnquiryHtml.indexOf("f_status") === -1);
assert.ok(fromEnquiryHtml.indexOf("Tuesday and Thursday") !== -1);
assert.ok(fromEnquiryHtml.indexOf("Office schedule") === -1);
assert.ok(fromEnquiryHtml.indexOf("Mark selected as important") !== -1);
assert.ok(officeJs.indexOf("/api/office/materials-to-order") !== -1);
assert.ok(officeJs.indexOf("/api/office/glass-po") !== -1);
assert.ok(officeJs.indexOf("/api/office/glass-po/receive") !== -1);
const toOrderHtml = fs.readFileSync(path.join(__dirname, "../public/orders-to-order.html"), "utf8");
assert.ok(toOrderHtml.indexOf("Generate purchase order PDF") !== -1);
assert.ok(toOrderHtml.indexOf("Order Number") !== -1);
assert.ok(toOrderHtml.indexOf("Glass type") !== -1);
assert.ok(toOrderHtml.indexOf("Thickness") !== -1);
assert.ok(toOrderHtml.indexOf(">Height<") !== -1);
assert.ok(toOrderHtml.indexOf(">Width<") !== -1);
assert.ok(toOrderHtml.indexOf("Quantity") !== -1);
assert.ok(toOrderHtml.indexOf("Purchase history") !== -1);
assert.ok(toOrderHtml.indexOf("openPoReview") !== -1);
assert.ok(toOrderHtml.indexOf("Specify template glass") !== -1);
assert.ok(toOrderHtml.indexOf("Estimated cost") !== -1);
assert.ok(toOrderHtml.indexOf("Actual cost") !== -1);
assert.ok(floor.indexOf("hasTemplateGlass") !== -1);
assert.ok(floor.indexOf("Has template glass") !== -1);
assert.ok(toOrderHtml.indexOf("/orders/glass-rates") !== -1);
assert.ok(toOrderHtml.indexOf("Receive selected") !== -1);
assert.ok(toOrderHtml.indexOf("Put the glass cost") !== -1);
assert.ok(toOrderHtml.indexOf("Mark ordered") !== -1, "wood still uses mark ordered");
assert.ok(indexJs.indexOf("/orders/glass-rates") !== -1);
assert.ok(officeJs.indexOf("/api/office/glass-rates") !== -1);
assert.ok(indexJs.indexOf("/orders/cost") !== -1);
assert.ok(officeJs.indexOf("/api/office/production-cost") !== -1);
assert.ok(officeJs.indexOf("/api/office/labour-rates") !== -1);
assert.ok(officeJs.indexOf("/api/office/steel-rates") !== -1);
const costHtml = fs.readFileSync(path.join(__dirname, "../public/orders-cost.html"), "utf8");
assert.ok(costHtml.indexOf("Production matrix") !== -1);
assert.ok(costHtml.indexOf("cost-matrix") !== -1);
assert.ok(costHtml.indexOf("col-product") !== -1);
assert.ok(costHtml.indexOf("left:90px") === -1);
assert.ok(costHtml.indexOf("left: 120px") === -1);
assert.ok(costHtml.indexOf("meta-pane") !== -1, "cost freezes Order and Product in a pane like production schedule");
assert.ok(costHtml.indexOf("id=\"logsMeta\"") !== -1);
assert.ok(costHtml.indexOf("id=\"logsScroller\"") !== -1);
assert.ok(costHtml.indexOf("overflow-x:hidden") !== -1);
assert.ok(costHtml.indexOf("overflow-x:auto") !== -1);
assert.ok(costHtml.indexOf("syncScrollY") !== -1);
assert.ok(costHtml.indexOf("Clear steel usage") !== -1);
assert.ok(costHtml.indexOf("Clear production log") !== -1);
assert.ok(costHtml.indexOf("/api/office/steel-usage/clear") !== -1);
assert.ok(costHtml.indexOf("/api/office/production-log/clear") !== -1);
assert.ok(officeJs.indexOf("/api/office/steel-usage/clear") !== -1);
assert.ok(officeJs.indexOf("/api/office/production-log/clear") !== -1);
assert.ok(officeJs.indexOf("clearSteelUsage") !== -1);
assert.ok(officeJs.indexOf("clearProductionLogs") !== -1);
assert.ok(costHtml.indexOf("Monthly order matrix") !== -1);
assert.ok(costHtml.indexOf("Steel cost") !== -1);
assert.ok(costHtml.indexOf("Labour rates") !== -1);
assert.ok(toOrderHtml.indexOf("/orders/cost") !== -1);
assert.ok(officeJs.indexOf("/api/office/glass-po/:poId/pdf") !== -1);
const glassRatesHtml = fs.readFileSync(path.join(__dirname, "../public/orders-glass-rates.html"), "utf8");
assert.ok(glassRatesHtml.indexOf("Rate per m²") !== -1);
assert.ok(glassRatesHtml.indexOf("Glass type") !== -1);
assert.ok(glassRatesHtml.indexOf("Thickness") !== -1);
assert.ok(officeJs.indexOf("/api/office/paint-shop") !== -1);
assert.ok(officeJs.indexOf("/api/office/paint-shop/receive") !== -1);
const paintShopHtml = fs.readFileSync(path.join(__dirname, "../public/orders-paint-shop.html"), "utf8");
assert.ok(paintShopHtml.indexOf("Send to paint shop") !== -1);
assert.ok(paintShopHtml.indexOf("Receive selected") !== -1);
assert.ok(paintShopHtml.indexOf("Put the paint shop cost") !== -1);
assert.ok(paintShopHtml.indexOf("invoice") !== -1);
assert.ok(floor.indexOf("glassOrderSection") !== -1);
assert.ok(floor.indexOf("Add another glass") !== -1);
assert.ok(floor.indexOf("This order has no glass") !== -1);
assert.ok(floor.indexOf("Use existing glass specification") !== -1);
assert.ok(floor.indexOf("woodRequired") !== -1);
assert.ok(floor.indexOf("openStationWork") !== -1, "tapping your station opens that task board");
assert.ok(floor.indexOf("myTaskStops") !== -1, "workers pick the task they are doing");
assert.ok(floor.indexOf("What are you doing now?") !== -1);
assert.ok(floor.indexOf("start-product-shot") !== -1, "start confirm shows the product image");
assert.ok(floor.indexOf("productShotHtml") !== -1, "floor cards show the product image");
assert.ok(floor.indexOf("hasFloorTask('Paint Preparation')") !== -1, "Ready for Assembly can go to paint prep");
assert.ok(floor.indexOf("hasFloorTask('Assembly')") !== -1, "Ready for Assembly can go to assembly");
assert.ok(floor.indexOf("START PAINT PREP") === -1, "painting is not a start choice on Ready for Assembly");
const roadAssembly = floor.indexOf("{ id: 'Assembly', role: 'Assembly', label: 'Assembly' }");
const roadPrep = floor.indexOf("{ id: 'Paint Preparation', role: 'Paint Preparation', label: 'Paint prep' }");
const roadPaint = floor.indexOf("{ id: 'Painting', role: 'Painting', label: 'Painting' }");
assert.ok(roadAssembly > -1 && roadPrep > roadAssembly && roadPaint > roadPrep, "paint loop sits after assembly on the task list");
assert.ok(floor.indexOf("getFloorTaskCounts") !== -1);
assert.ok(floor.indexOf("WORK_LOCKS_DISABLED") !== -1, "work lock can be turned off for testing");
assert.ok(floor.indexOf("Work lock is off for testing") !== -1);
const codeGs = fs.readFileSync(path.join(__dirname, "../Code.gs"), "utf8");
assert.ok(codeGs.indexOf("if (!start || !end) continue;") !== -1, "costing skips unfinished production logs");
assert.ok(codeGs.indexOf("var WORK_LOCKS_DISABLED = true") !== -1);
assert.ok(codeGs.indexOf("function workLocksDisabled") !== -1);
assert.ok(codeGs.indexOf("hourPart") !== -1 && codeGs.indexOf("minPart") !== -1, "task times speak hours and minutes");
assert.ok(codeGs.indexOf("minutesFromDurationHours") !== -1);
assert.ok(codeGs.indexOf("function resumeCountdownResult") !== -1);
assert.ok(codeGs.indexOf("'Painting': ['Ready for Painting', 'Painting']") !== -1, "painters only see the paint step");
assert.ok(codeGs.indexOf("sent to paint shop") !== -1);
assert.ok(codeGs.indexOf("Receive it on Paint shop") !== -1);
const durationsHtml = fs.readFileSync(path.join(__dirname, "../public/durations.html"), "utf8");
assert.ok(durationsHtml.indexOf("3.5 is 3 hours 30 minutes") !== -1);
assert.ok(durationsHtml.indexOf("hours: Math.round") !== -1);
assert.ok(durationsHtml.indexOf("minutesFromHours") === -1);
assert.ok(durationsHtml.indexOf("Minutes per product") === -1);
const planningHtml = fs.readFileSync(path.join(__dirname, "../public/planning.html"), "utf8");
assert.ok(planningHtml.indexOf("Auto - next open slot") !== -1);
assert.ok(planningHtml.indexOf("Journey") !== -1);
assert.ok(planningHtml.indexOf("Monday to Friday") !== -1 || planningHtml.indexOf("work days") !== -1);
assert.ok(planningHtml.indexOf("Schedule selected") !== -1);
assert.ok(planningHtml.indexOf(">Order<") !== -1 || planningHtml.indexOf("Order") !== -1);
assert.ok(planningHtml.indexOf("Person") !== -1);
assert.ok(planningHtml.indexOf("href=\"#people\"") !== -1, "People is a planning subpage");
assert.ok(planningHtml.indexOf("href=\"#journey\"") !== -1, "Journey is a planning subpage");
assert.ok(planningHtml.indexOf("href=\"#planning\"") !== -1, "Planning is a planning subpage");
assert.ok(planningHtml.indexOf("data-tab=\"planning\"") !== -1, "planning.html must have a Planning tab");
assert.ok(planningHtml.indexOf("data-tab=\"people\"") !== -1, "planning.html must have a People tab");
assert.ok(planningHtml.indexOf("data-tab=\"journey\"") !== -1, "planning.html must have a Journey tab");
assert.ok(planningHtml.indexOf("data-week") !== -1 && planningHtml.indexOf("data-day") !== -1, "Journey drills from week to day");
assert.ok(planningHtml.indexOf("15-minute") !== -1, "Journey day view opens a time grid");
assert.ok(planningHtml.indexOf("data-open-order") !== -1, "click an order number for its timeline");
assert.ok(planningHtml.indexOf("id='orderLife'") !== -1, "Journey order view loads the full enquiry-to-delivery path");
assert.ok(planningHtml.indexOf("fillOrderLife") !== -1);
assert.ok(planningHtml.indexOf("from enquiry through") !== -1);
assert.ok(planningHtml.indexOf("Name and Order swap while filtered") !== -1, "filtered day and time views put Name in front of Order");
assert.ok(planningHtml.indexOf("<th class='order'>Order</th><th class='name'>Name</th>") !== -1, "day and 15-minute grids keep Order and Name columns");
assert.ok(planningHtml.indexOf("not on this view") !== -1 || planningHtml.indexOf("Names are not on this view") !== -1, "weekly Journey hides names");
assert.ok(planningHtml.indexOf("freeze-names") !== -1 && planningHtml.indexOf("freeze-order") !== -1, "Order and Name columns freeze while the weeks scroll");
assert.ok(planningHtml.indexOf("Twenty shop weeks") !== -1, "Journey week view has more than five week columns");
assert.ok(planningHtml.indexOf("not Week 1 / 2 / 3") !== -1, "week headers are current shop dates, not example Week 1");
assert.ok(planningHtml.indexOf("th.week[data-week]") !== -1, "clicking a week header does not hide other orders");
assert.ok(planningHtml.indexOf("who starts first") !== -1, "Journey lists orders by start time");
assert.ok(planningHtml.indexOf("within an order") !== -1, "names on an order are listed by who works first");
assert.ok(planningHtml.indexOf("data-filter-worker") !== -1, "click a name on the day or 15-minute grid to see only that person");
assert.ok(planningHtml.indexOf("data-clear-worker") !== -1 && planningHtml.indexOf("← Everyone") !== -1, "filtered view can show everyone again");
assert.ok(planningHtml.indexOf("name-first") !== -1 && planningHtml.indexOf("<th class='name'>Name</th><th class='order'>Order</th>") !== -1, "filtered view swaps Name in front of Order");
assert.ok(planningHtml.indexOf('journeyLevel === "times" || journeyLevel === "days"') !== -1, "name filter works on day and 15-minute views");
assert.ok(planningHtml.indexOf("← Week view") !== -1 && planningHtml.indexOf("← Day view") !== -1, "Journey has back buttons to week and day views");
assert.ok(planningHtml.indexOf("rowspan") !== -1, "same order numbers are merged across people");
assert.ok(planningHtml.indexOf("C profile cutting") !== -1);
assert.ok(planningHtml.indexOf("<th class='kind'>Kind</th>") !== -1, "Journey has a Plan / Actual kind column");
assert.ok(planningHtml.indexOf(">Plan<") !== -1 && planningHtml.indexOf(">Actual<") !== -1, "each activity has a Plan row and an Actual row");
assert.ok(planningHtml.indexOf("function chipsForWeek") !== -1 && planningHtml.indexOf("function weekKindEntries") !== -1, "week view keeps an order’s tasks together on one Plan row and one Actual row");
assert.ok(planningHtml.indexOf("not on separate task rows") !== -1, "week-view help says tasks stay in the same cell");
assert.ok(planningHtml.indexOf('getAttribute("data-kind") === "actual"') !== -1, "Actual chips are marked so they are not dragged");
assert.ok(planningHtml.indexOf("if Cutting ran in week 2") !== -1, "Actual can sit in a later week than Plan");
assert.ok(planningHtml.indexOf("class='product") !== -1, "Journey shows the product under the order number");
assert.ok(planningHtml.indexOf("data-product-shot") !== -1 && planningHtml.indexOf("id=\"productShot\"") !== -1, "hover the product name to see the catalog photo");
assert.ok(planningHtml.indexOf("Hover the product name") !== -1, "week view tells you to hover the product");
assert.ok(planningHtml.indexOf('btn("plan", "Planned")') !== -1, "Journey can filter to Planned rows");
assert.ok(planningHtml.indexOf('btn("actual", "Actual")') !== -1, "Journey can filter to Actual rows");
assert.ok(planningHtml.indexOf("function setJourneyKind") !== -1, "Plan / Actual filter has a click handler");
assert.ok(planningHtml.indexOf("onclick='setJourneyKind") !== -1, "Plan / Actual buttons call the filter handler");
assert.ok(planningHtml.indexOf(".ghost { position:fixed") === -1, "outline ghost buttons must not use the drag-preview CSS");
assert.ok(planningHtml.indexOf("button.ghost") !== -1 && planningHtml.indexOf("pointer-events:auto") !== -1, "ghost buttons stay clickable");
assert.ok(planningHtml.indexOf("Show planned or actual") !== -1, "Planned / Actual filter is labelled");
assert.ok(planningHtml.indexOf("flex:1 1 100%") !== -1, "Plan / Actual buttons sit on their own row so they do not cover back links");
assert.ok(planningHtml.indexOf("Production Meeting") !== -1 && planningHtml.indexOf("Cleaning") !== -1, "People calendar must highlight Production Meeting and Cleaning");
assert.ok(planningHtml.indexOf("Compare with") !== -1, "People calendar must allow comparing two people");
assert.ok(planningHtml.indexOf("Add other task") !== -1, "People calendar can add other tasks");
assert.ok(planningHtml.indexOf("data-block") !== -1, "calendar events can be moved");
assert.ok(officeJs.indexOf("/api/office/planning/move") !== -1);
assert.ok(officeJs.indexOf("/api/office/planning/other") !== -1);
assert.ok(planningHtml.indexOf("Not Yet Started") !== -1);
assert.ok(planningHtml.indexOf("Ready for Steelwork") !== -1);
assert.ok(planningHtml.indexOf("Paint shop") !== -1 || planningHtml.indexOf("paintShop") !== -1);
assert.ok(planningHtml.indexOf("Office schedule") === -1);
assert.ok(indexJs.indexOf('"/planning"') !== -1 || indexJs.indexOf("/planning") !== -1);
assert.ok(officeJs.indexOf("/api/office/planning") !== -1);
assert.ok(floor.indexOf('href="/planning"') !== -1);
assert.ok(floor.indexOf("Planning") !== -1);
assert.ok(floor.indexOf("sd-qc-draft") !== -1, "QC forms keep a per-worker draft");
assert.ok(floor.indexOf("persistQcDraft") !== -1);
assert.ok(floor.indexOf("dropQcDraft") !== -1);
assert.ok(floor.indexOf("qcDraftPhotos") !== -1);
assert.ok(js.indexOf("sd-form-draft") !== -1, "office forms keep drafts on this device");
assert.ok(js.indexOf("sdWriteFormDraft") !== -1);
assert.ok(ordersHtml.indexOf("persistOrderDraft") !== -1);
assert.ok(officeJs.indexOf("applyOfficeOrderStatusLock") !== -1);
assert.ok(officeJs.indexOf("/api/office/job-cards") !== -1);
const jobCardHtml = fs.readFileSync(path.join(__dirname, "../public/job-card.html"), "utf8");
assert.ok(jobCardHtml.indexOf("/orders/paint-shop") !== -1);
assert.ok(jobCardHtml.indexOf("/orders/job-card/existing") !== -1);
assert.ok(jobCardHtml.indexOf("Generate job card") !== -1);
assert.ok(jobCardHtml.indexOf("Existing job cards") !== -1);
assert.ok(jobCardHtml.indexOf("Printed job cards") === -1);
const jobCardExistingHtml = fs.readFileSync(path.join(__dirname, "../public/job-card-existing.html"), "utf8");
assert.ok(jobCardExistingHtml.indexOf("Existing job cards") !== -1);
assert.ok(jobCardExistingHtml.indexOf("Open / print") !== -1);
assert.ok(jobCardExistingHtml.indexOf("/orders/paint-shop") !== -1);
assert.ok(jobCardHtml.indexOf("persistJobCardDraft") !== -1);
assert.ok(jobCardHtml.indexOf("Mark selected as important") !== -1);
assert.ok(jobCardHtml.indexOf("name=\"dimCheck\"") !== -1);
assert.ok(jobCardHtml.indexOf("Dimensions did not change") !== -1);
assert.ok(jobCardHtml.indexOf("Update to the actual dimensions") !== -1);
assert.ok(indexJs.indexOf("redirect(302, \"/orders/schedule\")") !== -1);
const deliveryHtml = fs.readFileSync(path.join(__dirname, "../public/orders-delivery.html"), "utf8");
assert.ok(deliveryHtml.indexOf("Delivery summary") !== -1);
assert.ok(deliveryHtml.indexOf("/orders/job-card") !== -1);
assert.ok(deliveryHtml.indexOf("/orders/paint-shop") !== -1);
assert.ok(deliveryHtml.indexOf("/api/office/schedule/delivery") !== -1);
assert.ok(deliveryHtml.indexOf("Filter by Week") !== -1);
assert.ok(deliveryHtml.indexOf("Latest Delivery") !== -1);
assert.ok(deliveryHtml.indexOf("Latest Courier") !== -1);
assert.ok(deliveryHtml.indexOf("it.status") !== -1, "status column is the order sheet status");
assert.ok(deliveryHtml.indexOf("it.codeLabel") === -1);
assert.ok(officeJs.indexOf("/api/office/schedule/delivery") !== -1);
assert.ok(floor.indexOf("Office schedule") === -1);
assert.ok(floor.indexOf("id=\"link-office-schedule\"") === -1);

const dashHtml = fs.readFileSync(path.join(__dirname, "../public/enquiries-dashboard.html"), "utf8");
assert.ok(dashHtml.indexOf("/enquiries/replies") !== -1);
assert.ok(dashHtml.indexOf("/enquiries/bookings") !== -1);

const repliesHtml = fs.readFileSync(path.join(__dirname, "../public/enquiries-replies.html"), "utf8");
assert.ok(repliesHtml.indexOf("Standard email replies") !== -1);
assert.ok(repliesHtml.indexOf("/api/office/enquiries/replies") !== -1);
assert.ok(repliesHtml.indexOf("Copy body") !== -1);
assert.ok(repliesHtml.indexOf("{{client_name}}") !== -1);
assert.ok(repliesHtml.indexOf("enqSearch") !== -1);
assert.ok(repliesHtml.indexOf("enquiry=") !== -1 || enquiriesHtml.indexOf("/enquiries/replies?enquiry=") !== -1);
assert.ok(enquiriesHtml.indexOf("Write email") !== -1);
assert.ok(enquiriesHtml.indexOf("/enquiries/replies?enquiry=") !== -1);
assert.ok(repliesHtml.indexOf("/enquiries/bookings") !== -1);
assert.ok(repliesHtml.indexOf("/sd-pwa.js?v=pwa") !== -1);
const bookingsHtml = fs.readFileSync(path.join(__dirname, "../public/enquiries-bookings.html"), "utf8");
assert.ok(bookingsHtml.indexOf("Showroom bookings") !== -1);
assert.ok(bookingsHtml.indexOf("/api/office/enquiries/bookings") !== -1);
assert.ok(bookingsHtml.indexOf("Book a visit") !== -1);
assert.ok(bookingsHtml.indexOf("Africa/Johannesburg") !== -1);
assert.ok(bookingsHtml.indexOf("Make enquiry") !== -1);
assert.ok(bookingsHtml.indexOf("Start quote") !== -1);
assert.ok(bookingsHtml.indexOf("/enquiry") !== -1);
assert.ok(officeJs.indexOf("transferVisit") !== -1);
assert.ok(bookingsHtml.indexOf("/enquiries/replies") !== -1);
assert.ok(indexJs.indexOf("/enquiries/replies") !== -1);
assert.ok(indexJs.indexOf("/enquiries/bookings") !== -1);
assert.ok(officeJs.indexOf("enquiry-desk") !== -1);
assert.ok(officeJs.indexOf("/api/office/enquiries/replies") !== -1);
assert.ok(officeJs.indexOf("/api/office/enquiries/bookings") !== -1);
assert.ok(dashHtml.indexOf("Weekly") !== -1);
assert.ok(dashHtml.indexOf("Monthly") !== -1);
assert.ok(dashHtml.indexOf("Revenue") !== -1);
assert.ok(dashHtml.indexOf("chart.js") !== -1);
assert.ok(dashHtml.indexOf("/api/office/enquiries/dashboard") !== -1);
assert.ok(dashHtml.indexOf("sdOfficeFetch") !== -1);
assert.ok(dashHtml.indexOf("CATERGORY") !== -1);
assert.ok(dashHtml.indexOf("id=\"month\"") !== -1);
assert.ok(dashHtml.indexOf("dashboard/drill") !== -1);
assert.ok(dashHtml.indexOf("sdOpenEnquiryProcess") !== -1);
assert.ok(dashHtml.indexOf("enquiry-process.js") !== -1);
assert.ok(dashHtml.indexOf("Quote value by type") !== -1);
assert.ok(dashHtml.indexOf("Week of month") !== -1);
assert.ok(dashHtml.indexOf("prodSearch") !== -1);
assert.ok(dashHtml.indexOf("Product value (excl VAT)") !== -1);
assert.ok(dashHtml.indexOf("Open work that still needs doing") !== -1);
assert.ok(dashHtml.indexOf("Follow-up only after 7 days") !== -1);
assert.ok(dashHtml.indexOf("/sd-pwa.js?v=pwa") !== -1, "dashboard must boot the PWA");
assert.ok(dashHtml.indexOf("qs(params)") !== -1, "week-of-month drill must send the clicked month");
assert.ok(dashHtml.indexOf("drillMoneyHtml") !== -1);
assert.ok(dashHtml.indexOf("Quoted excl VAT") !== -1);
assert.ok(dashHtml.indexOf("Ordered excl VAT") !== -1);
assert.ok(dashHtml.indexOf("moneyKpis") !== -1);
assert.ok(dashHtml.indexOf("close_reason") !== -1);
assert.ok(dashHtml.indexOf("Rejected because") !== -1);
assert.ok(dashHtml.indexOf("categoryScale") !== -1, "product bars must keep names on the category axis");
assert.ok(!/x: \{ beginAtZero: true, ticks: ticks \},\s*y: \{ beginAtZero: true, ticks: ticks \}/.test(dashHtml), "money ticks must not overwrite product names");
assert.ok(dashHtml.indexOf(">Outlook<") === -1, "Outlook pie must be replaced by quote value by type");

assert.ok(ordersHtml.indexOf("Import from Sheets") === -1, "Orders must not import from Google Sheets");
assert.ok(ordersHtml.indexOf("cell-text") !== -1);
assert.ok(ordersHtml.indexOf("armRow") === -1, "orders must edit through a form, not cells");
assert.ok(ordersHtml.indexOf("openForm") !== -1);
assert.ok(officeJs.indexOf("delete copy.payments") !== -1);
assert.ok(indexJs.indexOf("gzipSync") !== -1);
const gasJs = fs.readFileSync(path.join(__dirname, "gas.js"), "utf8");
assert.ok(gasJs.indexOf("workbookIsDirty") !== -1);
assert.ok(codeGs.indexOf("8000000") !== -1);
const adminFn = codeGs.slice(codeGs.indexOf("function getAdminDashboardData"), codeGs.indexOf("function getNextStatus"));
assert.ok(adminFn.indexOf("daySlices") === -1, "admin dashboard must not ship daySlices on every load");
const usersHtml = fs.readFileSync(path.join(__dirname, "../public/users.html"), "utf8");
assert.ok(usersHtml.indexOf("Enquiry roles") !== -1);
assert.ok(usersHtml.indexOf("job title") !== -1 || usersHtml.indexOf("Job title") !== -1);
assert.ok(usersHtml.indexOf("Manager") !== -1);
assert.ok(usersHtml.indexOf('list="jobTitles"') !== -1 || usersHtml.indexOf("list='jobTitles'") !== -1);
assert.ok(usersHtml.indexOf("data-k='manageUsers'") === -1, "Users table must not use a Manage users checkbox");
assert.ok(usersHtml.indexOf("Change access code") !== -1);
assert.ok(usersHtml.indexOf("/api/office/password") !== -1);
assert.ok(usersHtml.indexOf("data-role") !== -1);
assert.ok(usersHtml.indexOf('["Costing", "Quoting", "Approval", "Follow-up"]') !== -1);
assert.ok(usersHtml.indexOf("/users/backup") !== -1, "Users people page links to Backup subpage");
assert.ok(usersHtml.indexOf(">People<") !== -1);
assert.ok(usersHtml.indexOf("Download complete backup") === -1, "restore controls must not sit on People");
assert.ok(usersHtml.indexOf("backups/restore") === -1, "People page must not restore");
assert.ok(usersHtml.indexOf("migrate-from-google") !== -1);
const usersBackupHtml = fs.readFileSync(path.join(__dirname, "../public/users-backup.html"), "utf8");
assert.ok(usersBackupHtml.indexOf("Download JSON") !== -1);
assert.ok(usersBackupHtml.indexOf("Download SQLite") !== -1);
assert.ok(usersBackupHtml.indexOf("Backup now") !== -1);
assert.ok(usersBackupHtml.indexOf("Download complete backup") !== -1);
assert.ok(usersBackupHtml.indexOf("Type RESTORE") !== -1);
assert.ok(usersBackupHtml.indexOf("Manager access code") !== -1);
assert.ok(usersBackupHtml.indexOf("Confirm access code") !== -1);
assert.ok(usersBackupHtml.indexOf("/api/office/backups/run") !== -1);
assert.ok(usersBackupHtml.indexOf("backup.db") !== -1);
assert.ok(usersBackupHtml.indexOf("backup.tgz") !== -1);
assert.ok(usersBackupHtml.indexOf("backups/restore") !== -1);
assert.ok(usersBackupHtml.indexOf("x-sd-restore-password") !== -1);
assert.ok(usersBackupHtml.indexOf("BACKUP_DRIVE_FOLDER_ID") !== -1, "Backup page must explain how to turn Drive on");
assert.ok(usersBackupHtml.indexOf("Shared drive") !== -1, "Backup page must require a Shared drive");
assert.ok(usersBackupHtml.indexOf("/api/office/backups/drive-test") !== -1);
assert.ok(usersBackupHtml.indexOf("Send test file to Drive") !== -1);
assert.ok(usersBackupHtml.indexOf("href=\"/users\"") !== -1);
assert.ok(floor.indexOf('href="/enquiries"') !== -1);
assert.ok(floor.indexOf('href="/tasks"') !== -1);
assert.ok(floor.indexOf("resumeOfficeSession") !== -1);
assert.ok(floor.indexOf("function hideFloorPopover") !== -1, "twin render must be able to close the order popover");
assert.ok(floor.indexOf("officeLooksLoggedIn") !== -1, "Home must reuse the same-tab office session");
assert.ok(floor.indexOf("function adoptSavedSession") !== -1, "Home must reuse the saved session without a new login");
assert.ok(floor.indexOf('id="view-global-login"') !== -1 && /id="view-global-login"[^>]*d-none-view/.test(floor), "login must stay hidden until there is no session");
assert.ok(floor.indexOf("event.preventDefault(); goHome();") !== -1, "Home in the floor menu must not reload the tab");
assert.ok(floor.indexOf("navTo('view-roles')") !== -1);
assert.ok(floor.indexOf("sessionStorage.getItem('sd-session')") !== -1 || floor.indexOf('sessionStorage.getItem("sd-session")') !== -1);
assert.ok(floor.indexOf("sessionStorage.getItem('sd-office')") !== -1 || floor.indexOf('sessionStorage.getItem("sd-office")') !== -1);
assert.ok(floor.indexOf("showFloorLogin()") !== -1);
assert.ok(floor.indexOf("requestedView") !== -1);
assert.ok(floor.indexOf("sidebar-scroll") !== -1);
assert.ok(floor.indexOf("sdShowWelcome") !== -1);
assert.ok(floor.indexOf("welcome: true") !== -1);
assert.ok(floor.indexOf("sd-brand.css") !== -1);
assert.ok(floor.indexOf("sd-splash.js") !== -1);
assert.ok(floor.indexOf("paintBrandMarks") !== -1);
assert.ok(js.indexOf("sdShowWelcome") !== -1);
assert.ok(js.indexOf("sdSMark") !== -1);
assert.ok(js.indexOf("sdLoadBrand") !== -1);
assert.ok(js.indexOf("sd-login-card") !== -1);
assert.ok(indexJs.indexOf("/sd-brand.css") !== -1);
assert.ok(indexJs.indexOf("/sd-splash.js") !== -1);
assert.ok(indexJs.indexOf("/manifest.webmanifest") !== -1);
assert.ok(indexJs.indexOf("/sw.js") !== -1);
assert.ok(floor.indexOf("/sd-pwa.js?v=pwa") !== -1);
const splash = fs.readFileSync(path.join(__dirname, "../public/sd-splash.js"), "utf8");
assert.ok(splash.indexOf("Welcome to Studio Delta") !== -1);
assert.ok(splash.indexOf("sd-s") !== -1);
const brand = fs.readFileSync(path.join(__dirname, "../public/sd-brand.css"), "utf8");
assert.ok(brand.indexOf(".sd-welcome") !== -1);
assert.ok(brand.indexOf("#b08948") !== -1);
assert.ok(floor.indexOf("sd-erp-table") !== -1);
assert.ok(floor.indexOf("sd-page-head") !== -1);
assert.ok(floor.indexOf("count-notstarted") !== -1);
assert.ok(floor.indexOf("On floor") !== -1);
assert.ok(floor.indexOf("bootstrap.min.css") !== -1);
assert.ok(floor.indexOf('id="adminLinks"') !== -1);
assert.ok(floor.indexOf("safeNextPath") !== -1);
assert.ok(floor.indexOf("Shop floor") !== -1);
assert.ok(js.indexOf("sdForgetOffice") !== -1);
assert.ok(js.indexOf("sdShowLogin") !== -1);
assert.ok(js.indexOf("sessionStorage.getItem(\"sd-office\")") !== -1);
assert.ok(js.indexOf("localStorage.getItem(\"sd-office\")") === -1, "do not share login across tabs via localStorage");
assert.ok(js.indexOf("/api/office/me") !== -1);
assert.ok(js.indexOf('credentials: "same-origin"') !== -1 || js.indexOf("credentials: 'same-origin'") !== -1);
assert.ok(js.indexOf("await sdForgetOffice()") === -1, "do not log out when switching office pages");
assert.ok(js.indexOf("canSeeOffice") !== -1);

const debtorsHtml = fs.readFileSync(path.join(__dirname, "../public/debtors.html"), "utf8");
assert.ok(debtorsHtml.indexOf("PRODUCT") !== -1);
assert.ok(debtorsHtml.indexOf("/debtors/history") !== -1);
assert.ok(debtorsHtml.indexOf(">Owing<") !== -1);
assert.ok(debtorsHtml.indexOf(">History<") !== -1);
assert.ok(debtorsHtml.indexOf("type=\\\"file\\\"") !== -1);
assert.ok(debtorsHtml.indexOf("name=\\\"proof\\\"") !== -1);
assert.ok(debtorsHtml.indexOf("clientFilter") !== -1);
assert.ok(debtorsHtml.indexOf("Total excl VAT") !== -1);
assert.ok(debtorsHtml.indexOf("Total incl VAT") !== -1);
assert.ok(debtorsHtml.indexOf("sdRequireOffice(\"debtors\")") !== -1);
assert.ok(indexJs.indexOf("/debtors/history") !== -1);
assert.ok(officeJs.indexOf("listDebtorHistory") !== -1);
assert.ok(officeJs.indexOf("/api/office/debtors/history") !== -1);
assert.ok(officeJs.indexOf("/api/office/debtors/payments/") !== -1);
assert.ok(js.indexOf("/debtors/history") === -1, "history is a Debtors subpage, not a sidebar item");
assert.ok((js.match(/"\/debtors"/g) || []).length === 1, "Debtors stays one sidebar item");
assert.ok(indexJs.indexOf("/users/backup") !== -1);
assert.ok(js.indexOf("/users/backup") === -1, "Backup is a Users subpage, not a sidebar item");
assert.ok(officeJs.indexOf("checkRestoreSecrets") !== -1);
assert.ok(officeJs.indexOf("x-sd-restore-password") !== -1);

console.log("office-nav.test.js ok");
